package com.msa.professionalmap.feature.map.ui

internal object MapStyleIds {
    const val PoiSource = "professional-poi-source"
    const val PoiShadowLayer = "professional-poi-shadow"
    const val PoiSymbolLayer = "professional-poi-symbol"
    const val PoiLabelLayer = "professional-poi-label"
    const val PoiSelectedSource = "professional-poi-selected-source"
    const val PoiSelectedHaloLayer = "professional-poi-selected-halo"
    const val PoiSelectedCoreLayer = "professional-poi-selected-core"
    const val PoiSelectedSymbolLayer = "professional-poi-selected-symbol"
    const val PoiSelectedLabelLayer = "professional-poi-selected-label"
    const val ClusterShadowLayer = "professional-cluster-shadow"
    const val ClusterLayerSmall = "professional-cluster-small"
    const val ClusterLayerMedium = "professional-cluster-medium"
    const val ClusterLayerLarge = "professional-cluster-large"
    const val ClusterCountLayer = "professional-cluster-count"

    const val RouteAlternativesSource = "professional-route-alternatives-source"
    const val RouteHitLayer = "professional-route-hit-target"
    const val AlternativeRouteLayer = "professional-route-alternative"
    const val SelectedRouteCasingLayer = "professional-route-selected-casing"
    const val SelectedRouteLayer = "professional-route-selected"
    const val CompletedRouteSource = "professional-route-completed-source"
    const val CompletedRouteLayer = "professional-route-completed"
    const val RemainingRouteSource = "professional-route-remaining-source"
    const val RemainingRouteCasingLayer = "professional-route-remaining-casing"
    const val RemainingRouteLayer = "professional-route-remaining"
    const val SimplifiedRouteSource = "professional-route-simplified-source"
    const val SimplifiedRouteLayer = "professional-route-simplified"

    const val EndpointSource = "professional-route-endpoint-source"
    const val EndpointShadowLayer = "professional-route-endpoint-shadow"
    const val EndpointCircleLayer = "professional-route-endpoint-origin"
    const val EndpointDestinationLayer = "professional-route-endpoint-destination"
    const val EndpointLabelLayer = "professional-route-endpoint-label"
    const val ManeuverSource = "professional-maneuver-source"
    const val ManeuverCircleLayer = "professional-maneuver-circle"
    const val ManeuverLabelLayer = "professional-maneuver-label"

    const val SelectedPointSource = "professional-selected-point-source"
    const val SelectedPointHaloLayer = "professional-selected-point-halo"
    const val SelectedPointLayer = "professional-selected-point"
    const val ProjectedPointSource = "professional-projected-point-source"
    const val ProjectedPointLayer = "professional-projected-point"
    const val InstructionPointSource = "professional-instruction-point-source"
    const val InstructionPointLayer = "professional-instruction-point"

    const val UserLocationSource = "professional-user-location-source"
    const val UserLocationHaloLayer = "professional-user-location-halo"
    const val UserLocationLayer = "professional-user-location"
    const val UserHeadingSource = "professional-user-heading-source"
    const val UserHeadingLayer = "professional-user-heading"
    const val SnappedLocationSource = "professional-snapped-location-source"
    const val SnappedLocationLayer = "professional-snapped-location"

    const val PoiId = "poi_id"
    const val RouteId = "route_id"
    const val Title = "title"
    const val Subtitle = "subtitle"
    const val Category = "category"
    const val Selected = "selected"
    const val Label = "label"
    const val MarkerSymbol = "marker_symbol"
    const val PointCount = "point_count"
}
